<?php

return [
    'DZ' => ['+213', 'Algeria'],
    'AD' => ['+376', 'Andorra'],
    'AO' => ['+244', 'Angola'],
    'AI' => ['+1264', 'Anguilla'],
    'AG' => ['+1268', 'Antigua Barbuda'],
    'AR' => ['+54', 'Argentina'],
    'AM' => ['+374', 'Armenia'],
    'AW' => ['+297', 'Aruba'],
    'AU' => ['+61', 'Australia'],
    'AT' => ['+43', 'Austria'],
    'AZ' => ['+994', 'Azerbaijan'],
    'BS' => ['+1242', 'Bahamas'],
    'BH' => ['+973', 'Bahrain'],
    'BD' => ['+880', 'Bangladesh'],
    'BB' => ['+1246', 'Barbados'],
    'BY' => ['+375', 'Belarus'],
    'BE' => ['+32', 'Belgium'],
    'CA' => ['+1', 'Canada'],
    'FR' => ['+33', 'France'],
    'DE' => ['+49', 'Germany'],
    'IN' => ['+91', 'India'],
    'IL' => ['+972', 'Israel'],
    'IT' => ['+39', 'Italy'],
    'JP' => ['+81', 'Japan'],
    'KR' => ['+82', 'Korea South'],
    'MY' => ['+60', 'Malaysia'],
    'MX' => ['+52', 'Mexico'],
    'NL' => ['+31', 'Netherlands'],
    'NZ' => ['+64', 'New Zealand'],
    'SG' => ['+65', 'Singapore'],
    'ZA' => ['+27', 'South Africa'],
    'LK' => ['+94', 'Sri Lanka'],
    'SE' => ['+46', 'Sweden'],
    'TH' => ['+66', 'Thailand'],
    'GB' => ['+44', 'UK'],
    'US' => ['+1', 'USA'],
    'ZW' => ['+263', 'Zimbabwe']
];